[package]
name = "mauna_kea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.19.0"
eframe = "0.19.0"
regex = "1.6.0"
clipboard = "0.5.0"
reqwest = {version = "0.11.12", features = ["blocking"]}
colored = "2.0.0"
winapi = "0.3.9"
kernel32-sys = "0.2.2"
bitvec = "1.0.1"
image = "0.24.5"
